--- #YAML:1.0
name:               Dpchrist-Test
version:            1.006
abstract:           Perl module test utilities
author:
    - David Paul Christensen dpchrist@holgerdanske.com
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
